import Head from "next/head";
import type { NextPage } from "next";
import { css } from "@emotion/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>My Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <p
          css={css`
            color: aqua;
          `}
        >
          Test
        </p>
      </main>
    </>
  );
};

export default Home;
